import { AbstractRuleTree, CompiledOutput } from '../../types/index.js';

export function compileAgents(art: AbstractRuleTree, headerComment: boolean = true): CompiledOutput {
  const header = headerComment
    ? `<!-- Auto-generated by RuleSync (https://github.com/rulesync/rulesync) - DO NOT EDIT DIRECTLY -->\n\n`
    : '';

  let out = `${header}# ${art.title}\n\n`;

  if (art.overview) {
    out += `${art.overview}\n\n`;
  }

  for (const rule of art.rules) {
    out += `## ${rule.metadata.title}\n`;
    if (rule.metadata.globs && rule.metadata.globs.length > 0) {
      out += `<!-- globs: ${rule.metadata.globs.join(', ')} -->\n`;
    }
    if (rule.metadata.tools && rule.metadata.tools.length > 0) {
      out += `<!-- tools: ${rule.metadata.tools.join(', ')} -->\n`;
    }
    out += `${rule.content}\n\n`;
  }

  return {
    target: 'agents',
    relativePath: 'AGENTS.md',
    content: out.trim() + '\n',
  };
}
