import { AbstractRuleTree, CompiledOutput } from '../../types/index.js';

export function compileCopilot(art: AbstractRuleTree, headerComment: boolean = true): CompiledOutput {
  const header = headerComment
    ? `<!-- Auto-generated by RuleSync (https://github.com/rulesync/rulesync) - DO NOT EDIT DIRECTLY -->\n\n`
    : '';

  let out = `${header}# ${art.title}\n\n`;

  if (art.overview) {
    out += `${art.overview}\n\n`;
  }

  out += `## GitHub Copilot Repository Instructions\n\n`;

  for (const rule of art.rules) {
    out += `### ${rule.metadata.title}\n`;
    if (rule.metadata.globs && rule.metadata.globs.length > 0) {
      out += `*Applicable files: \`${rule.metadata.globs.join(', ')}\`*\n\n`;
    }
    out += `${rule.content}\n\n`;
  }

  return {
    target: 'copilot',
    relativePath: '.github/copilot-instructions.md',
    content: out.trim() + '\n',
  };
}
