import { AbstractRuleTree, CompiledOutput } from '../../types/index.js';

export function compileCursor(art: AbstractRuleTree, headerComment: boolean = true): CompiledOutput {
  const header = headerComment
    ? `<!-- Auto-generated by RuleSync (https://github.com/rulesync/rulesync) - DO NOT EDIT DIRECTLY -->\n\n`
    : '';

  const globsJson = JSON.stringify(art.globalGlobs || ['*']);

  let mdc = `---\ndescription: ${art.title}\nglobs: ${globsJson}\nalwaysApply: true\n---\n\n`;
  mdc += `${header}# ${art.title}\n\n`;

  if (art.overview) {
    mdc += `${art.overview}\n\n`;
  }

  for (const rule of art.rules) {
    mdc += `## ${rule.metadata.title}\n`;
    if (rule.metadata.globs && rule.metadata.globs.length > 0) {
      mdc += `> Applies to: \`${rule.metadata.globs.join(', ')}\`\n\n`;
    }
    mdc += `${rule.content}\n\n`;
  }

  return {
    target: 'cursor',
    relativePath: '.cursor/rules/rulesync.mdc',
    content: mdc.trim() + '\n',
  };
}
