import { AbstractRuleTree, CompiledOutput } from '../../types/index.js';

export function compileWindsurf(art: AbstractRuleTree, headerComment: boolean = true): CompiledOutput {
  const header = headerComment
    ? `<!-- Auto-generated by RuleSync (https://github.com/rulesync/rulesync) - DO NOT EDIT DIRECTLY -->\n\n`
    : '';

  let out = `${header}# ${art.title} (Windsurf Rules)\n\n`;

  if (art.overview) {
    out += `${art.overview}\n\n`;
  }

  for (const rule of art.rules) {
    out += `- **${rule.metadata.title}**`;
    if (rule.metadata.globs && rule.metadata.globs.length > 0) {
      out += ` (\`${rule.metadata.globs.join(', ')}\`)`;
    }
    out += `: ${rule.content.replace(/\n+/g, ' ')}\n`;
  }

  return {
    target: 'windsurf',
    relativePath: '.windsurfrules',
    content: out.trim() + '\n',
  };
}
